//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverParse.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OverParse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Always on top 的當地語系化字串。
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto-End Encounters 的當地語系化字串。
        /// </summary>
        public static string AutoEnd {
            get {
                return ResourceManager.GetString("AutoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto-hide window 的當地語系化字串。
        /// </summary>
        public static string AutoHide {
            get {
                return ResourceManager.GetString("AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 List Opacity 的當地語系化字串。
        /// </summary>
        public static string BackOp {
            get {
                return ResourceManager.GetString("BackOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 はい、インストールを続けます 的當地語系化字串。
        /// </summary>
        public static string BanCheck {
            get {
                return ResourceManager.GetString("BanCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OverParse is a 3rd-party tool that breaks PSO2&apos;s Terms and Conditions.
        ///SEGA has confirmed in an official announcement that accounts found using parsing tools may be banned.
        ///If account safety is your first priority, do NOT use OverParse. You use this tool entirely at your own risk.
        ///Would you like to continue with setup? 的當地語系化字串。
        /// </summary>
        public static string BanWarning {
            get {
                return ResourceManager.GetString("BanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Could not save data to clipboard. 的當地語系化字串。
        /// </summary>
        public static string Cantclip {
            get {
                return ResourceManager.GetString("Cantclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Font 的當地語系化字串。
        /// </summary>
        public static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change .csv update interval 的當地語系化字串。
        /// </summary>
        public static string Changeinv {
            get {
                return ResourceManager.GetString("Changeinv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable GPU Rendering 的當地語系化字串。
        /// </summary>
        public static string CPUDraw {
            get {
                return ResourceManager.GetString("CPUDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taken 的當地語系化字串。
        /// </summary>
        public static string Damaged {
            get {
                return ResourceManager.GetString("Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discard Encounter (No Log) 的當地語系化字串。
        /// </summary>
        public static string DiscardEncounter {
            get {
                return ResourceManager.GetString("DiscardEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setup is complete. Please restart PSO2 if it is already running. 的當地語系化字串。
        /// </summary>
        public static string Donedll {
            get {
                return ResourceManager.GetString("Donedll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change DPS Display Format 的當地語系化字串。
        /// </summary>
        public static string DPSFormat {
            get {
                return ResourceManager.GetString("DPSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End Encounter 的當地語系化字串。
        /// </summary>
        public static string EndEncounter {
            get {
                return ResourceManager.GetString("EndEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error has occured during setup. Please check that PSO2 is not running and that OverParse has read/write permissions. 的當地語系化字串。
        /// </summary>
        public static string Errordll {
            get {
                return ResourceManager.GetString("Errordll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide A.I.S. 的當地語系化字串。
        /// </summary>
        public static string HideAIS {
            get {
                return ResourceManager.GetString("HideAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide Dark Blast 的當地語系化字串。
        /// </summary>
        public static string HideDB {
            get {
                return ResourceManager.GetString("HideDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide Laconium Sword 的當地語系化字串。
        /// </summary>
        public static string HideLsw {
            get {
                return ResourceManager.GetString("HideLsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Anonymize Names 的當地語系化字串。
        /// </summary>
        public static string HideName {
            get {
                return ResourceManager.GetString("HideName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide Enemy/NPCs 的當地語系化字串。
        /// </summary>
        public static string HideNPC {
            get {
                return ResourceManager.GetString("HideNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide Players 的當地語系化字串。
        /// </summary>
        public static string HidePlayer {
            get {
                return ResourceManager.GetString("HidePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide Photon Weapons 的當地語系化字串。
        /// </summary>
        public static string HidePwp {
            get {
                return ResourceManager.GetString("HidePwp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide Rideroid 的當地語系化字串。
        /// </summary>
        public static string HideRide {
            get {
                return ResourceManager.GetString("HideRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Higlight Self 的當地語系化字串。
        /// </summary>
        public static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 dll plugin install now? 的當地語系化字串。
        /// </summary>
        public static string Installdll {
            get {
                return ResourceManager.GetString("Installdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PSO2DamageDump
        ///- - - - - - -
        ///PSO2DamageDump
        ///https://github.com/VariantXYZ/PSO2DamageDump
        ///
        ///
        ///OverParse
        ///- - - - - - -
        ///OverParse
        ///https://github.com/TyroneSama/OverParse
        ///
        ///
        ///
        ///ColorPickerWPF / MIT License
        ///- - - - - - -
        ///ColorPickerWPF
        ///https://github.com/drogoganor/ColorPickerWPF
        ///
        ///Copyright (c) 2017 drogoganor
        ///
        ///https://opensource.org/licenses/MIT
        ///
        ///
        ///
        ///Google Noto Fonts / SIL Open Font License
        ///- - - - - - -
        ///Noto fonts
        ///https://github.com/googlei18n/noto-fonts
        ///
        ///https://www.google.com/get/noto/ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string License1 {
            get {
                return ResourceManager.GetString("License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Low Priority Mode 的當地語系化字串。
        /// </summary>
        public static string LowResources {
            get {
                return ResourceManager.GetString("LowResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OverParse requires PSO2DamageDump.dll in order to recieve damage logs. 的當地語系化字串。
        /// </summary>
        public static string Needdll {
            get {
                return ResourceManager.GetString("Needdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This release of OverParse includes a new version of the parsing plugin. Would you like to update now? 的當地語系化字串。
        /// </summary>
        public static string Newdll {
            get {
                return ResourceManager.GetString("Newdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 That doesn&apos;t appear to be a valid pso2_bin directory.
        ///If you installed the game using default settings, it will probably be in C:\\PHANTASYSTARONLINE2\pso2_bin\.
        ///Otherwise, find the location you installed to. 的當地語系化字串。
        /// </summary>
        public static string Noexe {
            get {
                return ResourceManager.GetString("Noexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OverParse needs a valid PSO2 installation to function.
        ///The application will now close. 的當地語系化字串。
        /// </summary>
        public static string Noinstall {
            get {
                return ResourceManager.GetString("Noinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No logs recorded in this session. 的當地語系化字串。
        /// </summary>
        public static string NoLogs {
            get {
                return ResourceManager.GetString("NoLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open Logs Folder 的當地語系化字串。
        /// </summary>
        public static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset Window Size 的當地語系化字串。
        /// </summary>
        public static string ResizeWindow {
            get {
                return ResourceManager.GetString("ResizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Round JA/Crit Percents 的當地語系化字串。
        /// </summary>
        public static string RoundJA {
            get {
                return ResourceManager.GetString("RoundJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select your pso2_bin directory. OverParse uses this to read your damage logs. 的當地語系化字串。
        /// </summary>
        public static string Selectbin {
            get {
                return ResourceManager.GetString("Selectbin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select your pso2_bin directory. OverParse uses this to read your damage logs. 的當地語系化字串。
        /// </summary>
        public static string Selectbox {
            get {
                return ResourceManager.GetString("Selectbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Column 的當地語系化字串。
        /// </summary>
        public static string SelectColumn {
            get {
                return ResourceManager.GetString("SelectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Damage Separation 的當地語系化字串。
        /// </summary>
        public static string Separate {
            get {
                return ResourceManager.GetString("Separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate A.I.S. 的當地語系化字串。
        /// </summary>
        public static string SeparateAIS {
            get {
                return ResourceManager.GetString("SeparateAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate Dark Blast 的當地語系化字串。
        /// </summary>
        public static string SeparateDB {
            get {
                return ResourceManager.GetString("SeparateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate HTF 的當地語系化字串。
        /// </summary>
        public static string SeparateHTF {
            get {
                return ResourceManager.GetString("SeparateHTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate Laconium Sword 的當地語系化字串。
        /// </summary>
        public static string SeparateLsw {
            get {
                return ResourceManager.GetString("SeparateLsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate Photon Weapons 的當地語系化字串。
        /// </summary>
        public static string SeparatePwp {
            get {
                return ResourceManager.GetString("SeparatePwp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate Rideroid 的當地語系化字串。
        /// </summary>
        public static string SeparateRide {
            get {
                return ResourceManager.GetString("SeparateRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Separate Zanverse 的當地語系化字串。
        /// </summary>
        public static string SeparateZanverse {
            get {
                return ResourceManager.GetString("SeparateZanverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Session Logs 的當地語系化字串。
        /// </summary>
        public static string SessionLog {
            get {
                return ResourceManager.GetString("SessionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Damage Graph 的當地語系化字串。
        /// </summary>
        public static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Skip DLL Update 的當地語系化字串。
        /// </summary>
        public static string Skipdll {
            get {
                return ResourceManager.GetString("Skipdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clickthrough Toggle 的當地語系化字串。
        /// </summary>
        public static string ThroughClick {
            get {
                return ResourceManager.GetString("ThroughClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide All Other Players 的當地語系化字串。
        /// </summary>
        public static string ThroughOther {
            get {
                return ResourceManager.GetString("ThroughOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set Encounter Timeout 的當地語系化字串。
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy Log to Clipboard 的當地語系化字串。
        /// </summary>
        public static string ToClip {
            get {
                return ResourceManager.GetString("ToClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TScore 的當地語系化字串。
        /// </summary>
        public static string TScore {
            get {
                return ResourceManager.GetString("TScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update skills.csv 的當地語系化字串。
        /// </summary>
        public static string Updatecsv {
            get {
                return ResourceManager.GetString("Updatecsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show UI Updated Time(Debug) 的當地語系化字串。
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Variable Column 的當地語系化字串。
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove non-combat time 的當地語系化字串。
        /// </summary>
        public static string VideoTime {
            get {
                return ResourceManager.GetString("VideoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Attack Mode Separation 的當地語系化字串。
        /// </summary>
        public static string VSeparate {
            get {
                return ResourceManager.GetString("VSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window Opacity 的當地語系化字串。
        /// </summary>
        public static string WinOp {
            get {
                return ResourceManager.GetString("WinOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Write the TScore to the log 的當地語系化字串。
        /// </summary>
        public static string WriteTScore {
            get {
                return ResourceManager.GetString("WriteTScore", resourceCulture);
            }
        }
    }
}
